import {
  ArrowRight,
  CheckCircle,
  FileText,
  GitBranch,
  ShieldCheck,
  Warning
} from "@phosphor-icons/react/ssr";
import { buildReportFromRepo } from "@aryam/fixmap-core/browser";
import { sampleRepo } from "../sample-repo";

const task = "TOKEN_TTL_MINUTES is ignored and reset links expire immediately.";
const command = `fixmap plan --issue "${task}" --format agent`;
const report = buildReportFromRepo(sampleRepo, { issueText: task, limit: 3 });

function homepageExample() {
  const editCandidate = report.contextFiles[0];
  const impactFile = (report.impact?.files ?? []).find((file) => !file.path.includes("test/"));
  const testRoute = report.testRoutes[0];
  const risk = report.risks[0];

  if (!editCandidate || !impactFile || !testRoute || !risk) {
    throw new Error("The homepage example no longer contains the file, test, impact, and risk evidence it is designed to explain.");
  }

  return { editCandidate, impactFile, testRoute, risk };
}

const { editCandidate, impactFile, testRoute, risk } = homepageExample();

const candidateReason =
  editCandidate.reasons.find((reason) => reason.startsWith("defines task identifiers")) ??
  editCandidate.reasons[0] ?? "ranked repository evidence";
const impactReason = impactFile.evidence[0]?.reason ?? "related repository evidence";

export function InteractiveMapStage() {
  return (
    <figure className="real-report-stage" aria-labelledby="real-report-title">
      <figcaption className="real-report-toolbar" id="real-report-title">
        <span><ShieldCheck size={18} weight="duotone" aria-hidden /><strong>Real FixMap output</strong></span>
        <span>sample-api · local checkout</span>
      </figcaption>

      <div className="real-report-flow">
        <section className="real-report-input" aria-label="Input to FixMap">
          <span className="real-report-label">You provide</span>
          <strong>Your coding task</strong>
          <blockquote>{task}</blockquote>
          <div className="real-report-repo"><GitBranch size={17} aria-hidden /><span><b>Repository</b> sample-api</span></div>
          <code>{command}</code>
        </section>

        <div className="real-report-bridge" aria-label="FixMap maps the task to repository evidence">
          <span>FixMap maps repository evidence</span>
          <ArrowRight size={22} weight="bold" aria-hidden />
        </div>

        <section className="real-report-output" aria-label="Output from FixMap">
          <span className="real-report-label">Your agent gets</span>
          <strong>Focused places to inspect first</strong>
          <dl>
            <div>
              <dt><FileText size={19} weight="duotone" aria-hidden /> File candidate</dt>
              <dd><code>{editCandidate.path}</code><span>{candidateReason}</span></dd>
            </div>
            <div>
              <dt><CheckCircle size={19} weight="fill" aria-hidden /> Test</dt>
              <dd><code>{testRoute.command}</code><span>{testRoute.relatedFiles[0]}</span></dd>
            </div>
            <div>
              <dt><GitBranch size={19} weight="duotone" aria-hidden /> Impact &amp; risk</dt>
              <dd>
                <code>{impactFile.path}</code>
                <span>{impactReason}</span>
                <span className="real-report-risk"><Warning size={14} aria-hidden /><b>{risk.area}</b> · {risk.reason}</span>
              </dd>
            </div>
          </dl>
        </section>
      </div>

      <p className="real-report-footnote">
        Generated by the real browser-safe FixMap engine against the sample repository used in the live demo.
      </p>
    </figure>
  );
}
